apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-server
  type: LoadBalancer
  ports:
  - port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 8080;
      index index.php index.html;
      root /usr/share/nginx/html;
    }
  index.html: |
    Code.education Rocks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      volumes:
      - name: nginx-data
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: www-data
        configMap:
          name: nginx-conf
          items:
            - key: index.html
              path: index.html
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-data
            readOnly: true
          - mountPath: /usr/share/nginx/html
            name: www-data
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
